# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
FSHOnly: true

id: intrahealth.simple-hiv-ig
canonical: https://github.com/intrahealth/simple-hiv-ig
version: 0.1.0
name: SimpleHIVImplementationGuide
title: Simple HIV Implementation Guide
status: draft
publisher: IntraHealth International
contact:
  - name: IntraHealth International
  - url: www.intrahealth.org
description: Simple HIV Implementation Guide for CQL Testing (non-normative)
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
  path-binary: input/cql/
copyrightYear: 2020+
releaseLabel: ci-build
# menu:
#   IG Home: index.html
#   Table of Contents: toc.html
#   Artifacts Summary: artifacts.html
#   Other Resources:
#     "FHIR Spec ": new-tab {{site.data.fhir.path}}index.html
dependencies:
  hl7.fhir.uv.ips: 1.0.0
  hl7.fhir.uv.sdc: current